services:
  mysql:
    image: mysql:latest
    container_name: sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: labfinal
      MYSQL_DATABASE: Library Management System # change as you need
    ports:
      - "3306:3306"
    # volumes:
      # - ./mysql_data:/var/lib/mysql
