services:
  mysql:
    image: mysql:latest
    container_name: sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: arasruislam
      MYSQL_DATABASE: study
    ports:
      - "3306:3306"
    # volumes:
      # - ./mysql_data:/var/lib/mysql
